### ISSUE TITLE
[8.0/Master] Feature Request - Full Text Search > website / website_sale / website_forum / website_blog / website_event

### ISSUE THREAD

**Issue by lukebranch** [Therp/fulltextsearch#1]
These modules look very useful. Are there any plans to extend the FTS modules to include modules for the website / website_sale / website_forum / website_blog / website_event modules?

I think FTS would be very useful for the frontend website modules. Being able to have a single unified search field that searches everything on the frontend website modules would also definitely be a plus.

**Comment by hbrunn** [comment]
Not from our side, but PRs are welcome

**Comment by lukebranch** [comment]
@hbrunn ,

Thanks for the quick reply. I'll look into the module structure in more detail when I can find time and submit a PR once I have something workable.

**Comment by hbrunn** [comment]
It can be pretty simple as in https://github.com/Therp/fulltextsearch/blob/7.0/fts_document/fts_document.py (the fact that it inherits from fts_base does all the magic) - but there are some UI tweaks I never tested on 8.0 and you probably want to show the search in the frontend, so this would have to be implemented as it's currently backend only.
